---
title: "wrangling"
author: "Ang Sonam Sherpa"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(janitor)
library(gganimate)
```


```{r, Open Data Nepal Project}


cand2013 <- read_csv("raw_data/cand2013.csv",
                     col_types = 
                       cols(District = col_character(),
                            Zone = col_factor(),
                            `Geographical Region` = col_factor(),
                            `Development Region` = col_factor(),
                            Constituency = col_double(),
                            CandidateName = col_character(),
                            Gender = col_character(),
                            Age = col_double(),
                            PartyName = col_factor()
                            )) %>%
  clean_names() %>%

# The major problem with this data set was its inconsistent use of Nepali and
# English. I initially extracted for the gender column in R, and then I copied
# the Nepali terms to selectively exchange the respective genders in the data
# set with the case when function.
  
  mutate(gender = case_when(gender == "рдо" ~ "female",
                            TRUE ~ "male")) %>%
                        
# I then got rid of the candidate's name because they were irrelevant to my
# analysis.

  select(!candidate_name)


# I am reading all the data sets into R, and using clean names function from 
# the janitor package to clean their column names. I only selected district and
# gender because I did not need anything else.

results2008 <- read_csv("raw_data/results2008.csv",
                        col_types = cols(
  District = col_character(),
  Zone = col_character(),
  `Geographical Region` = col_character(),
  `Development Region` = col_character(),
  S.no = col_double(),
  Const = col_double(),
  `Candidate Name` = col_character(),
  `Party Name` = col_character(),
  Gender = col_character(),
  `Total Votes` = col_double(),
  Remark = col_character())) %>%
  clean_names() %>%
  select(district, gender)

# reading in the dropout data set of school dropout rates in 2011-12

dropout <- read.csv("raw_data/dropout_rates_2011-012.csv") %>%
  clean_names()

```


```{r, Nepal in Data}


# I renamed all the columns with apt names and selected the 2011 columns only
# since I only needed them for my analyses.

# I have not converted the columns into numeric yet, because I have done so
# after I merged them. No particular reason, simply for convenience.

femaleliteracy <- read_csv("raw_data/femaleliteracy.csv",
                           col_types = cols(
  District = col_character(),
  `2001` = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(femaleliteracy2011 = x2011) %>%
  select(femaleliteracy2011, district)
  
femalepop <- read_csv("raw_data/femalepop.csv",
                      col_types = cols(
  District = col_character(),
  `2001` = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(femalepop2011 = x2011) %>%
  select(femalepop2011, district)

hdi2011 <- read_csv("raw_data/hdi2011.csv",
                    col_types = cols(
  District = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(hdi2011 = x2011)

literacy <- read_csv("raw_data/literacy.csv",
                     col_types = cols(
  District = col_character(),
  `2001` = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(literacy2011 = x2011) %>%
  select(literacy2011, district)

popdensity <- read_csv("raw_data/popdensity.csv",
                       col_types = cols(
  District = col_character(),
  `2001` = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(popdens2011 = x2011) %>%
  select(popdens2011, district)

povline <- read_csv("raw_data/povlineprop.csv",
                    col_types = cols(
  District = col_character(),
  `2004` = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(povline2011 = x2011) %>%
  select(povline2011, district)

totalpop <- read_csv("raw_data/totalpop.csv",
                     col_types = cols(
  District = col_character(),
  `2001` = col_character(),
  `2011` = col_character())) %>%
  clean_names() %>%
  rename(pop2011 = x2011) %>%
  select(pop2011, district)

administrativejobs <- read_csv("raw_data/womenadministrativejob.csv",
                               col_types = cols(
  District = col_character(),
  `2001` = col_character())) %>%
  clean_names() %>%
  rename(adminjobs2001 = x2001)

professionaljobs <- read_csv("raw_data/womenprofessionaljob.csv",
                             col_types = cols(
  District = col_character(),
  `2001` = col_character())) %>%
  clean_names() %>%
  rename(professionaljobs2001 = x2001)

incomeshare <- read_csv("raw_data/womenincomeshare.csv",
                        col_types = cols(
  District = col_character(),
  `2001` = col_character())) %>%
  clean_names() %>%
  rename(income2001 = x2001)

# I received a lot of error while reading all these data in. I realized
# after some looking aorund that it was a problem with the data set itself.
# I decided to ignore the errors because it was simply a matter of two
# districts not have all the information.

```


```{r, combining variable data sets}

# I removed the districts in all these data sets, which I believe were a
# a result of redistricting recently. All of them have na values, which most
# likely means they simply did not exist when these data sets were collected
# in 2001 and 2011.

variables <- incomeshare %>%
  full_join(professionaljobs, by = "district") %>%
  full_join(administrativejobs, by = "district") %>%
  full_join(totalpop, by = "district") %>%
  full_join(povline, by = "district") %>%
  full_join(popdensity, by = "district") %>%
  full_join(literacy, by = "district") %>%
  full_join(hdi2011, by = "district") %>%
  full_join(femalepop, by = "district") %>%
  full_join(femaleliteracy, by = "district") %>%
  arrange(income2001) %>%
  head(72) %>%
  
# I used head 72 to remove the four redistricting cases, and also all the
# unnecessary data rows with previous variables.  
  
  mutate(pop2011 = as.numeric(pop2011),
         povline2011 = as.numeric(povline2011),
         popdens2011 = as.numeric(popdens2011),
         literacy2011 = as.numeric(literacy2011),
         hdi2011 = as.numeric(hdi2011),
         femalepop2011 = as.numeric(femalepop2011),
         femaleliteracy2011 = as.numeric(femaleliteracy2011),
         professionaljobs2001 = as.numeric(professionaljobs2001),
         adminjobs2001 = as.numeric(adminjobs2001),
         income2001 = as.numeric(income2001))

# I also used mutate to change the type of these columns into numeric as I
# wanted them to be for the model.

# I got an error here saying that NAs were introduced by coercion. That was
# the case because "NA" were literaly written as characters in these cells
# before, which made R act as suh.

```


```{r, combining all the data sets}

# combining results of 2008 with the data set of candidates from 2013.

# I initially used full_join, but it created a data set with 30000 rows. It
# simply multiplied the number of districts in 2013 by the number of candidates
# from each district. To avoid this, I changed the variable in the 2008 from
# individual candidate to a district proportion of female winners.

# created an object to store the proportion of women

prop2008 <- results2008 %>%
  group_by(district) %>%
  mutate(gender = case_when(gender == "F" ~ 1,
                            TRUE ~ 0)) %>%
  summarize(winner2008 = sum(gender)/n(), .groups = "drop")

# joined the object to cand2013 using full join so that I do not miss any data

cand2013 <- cand2013 %>%
  full_join(prop2008, by = "district") %>%
  full_join(dropout, by = "district")

# combining candidates data set with variables data set

# Since the data sets of candidates and these variable data sets are from
# different sources, I explored their differences before joining them together.
# Lo and Behold, there were some districts that were not present in the
# variables data set. It should be because of a problem with the source data.

# To figure out the missing districts, I created objects with district names
# from each data set.

cand <- unique(cand2013$district)

var <- unique(variables$district)

# I then created an object with the difference using the %in% operator.

difference <- tibble(district = cand[!(cand %in% var)])

# Joined the candidate and the variables data set using full join to make sure
# that I do not lose any important data points

cand2013 <- cand2013 %>%
  full_join(variables, by = "district")

# Removed the districts in the difference tibble using anti join. I tried
# filtering but it did not work out. Anti join gives us value from the first
# data set that are not present in the second.

cand2013 <- anti_join(cand2013, difference, by = "district")

# Adding the proportion of female candidates in every district in 2013 and
# joining it to the original data set using full join.

prop2013 <- cand2013 %>%
  group_by(district) %>%
  mutate(gender = case_when(gender == "female" ~ 1,
                            TRUE ~ 0)) %>%
  summarize(prop2013 = sum(gender)/n(), .groups = "drop")

cand2013 <- cand2013 %>%
  full_join(prop2013, by = "district") %>%
  drop_na()

# I noticed after plotting some graphs that there were some gender values
# unavailable for some candidates. I removed these na values for proper
# modeling and graphing.

```


```{r, aggreagate data set}

# Creating an aggregate data set consisting of only district characteristics
# and district proportions of women candidates from 2013 and women winners
# from 2008

aggregate <- cand2013 %>%
  select(- c(age, party_name, gender, constituency)) %>%
  unique()

```


```{r, writing csv files}

# writing csv files for easy access and faster loading in the main app

write.csv(cand2013, "cand2013")
write.csv(aggregate, "aggregate")

```


```{r}

# world bank data about South Asia
# selected the relevant columns only
# used clean names from the janitor package

worldbank <- read.csv(
 "raw_data/a3bcc4fa-187c-4afe-a299-1961956028d5_Data.csv"
 ) %>%
  clean_names() %>%
  select(series_name, country_name, x1960_yr1960,
         x1961_yr1961, x1962_yr1962, x1963_yr1963, 
         x1964_yr1964, x1965_yr1965, x1966_yr1966, 
         x1967_yr1967, x1968_yr1968, x1969_yr1969,
         x1970_yr1970, 
         x1971_yr1971, x1972_yr1972, x1973_yr1973, 
         x1974_yr1974, x1975_yr1975, x1976_yr1976, 
         x1977_yr1977, x1978_yr1978, x1979_yr1979, 
         x1980_yr1980, x1981_yr1981, x1982_yr1982, 
         x1983_yr1983, x1984_yr1984, x1985_yr1985, 
         x1986_yr1986, x1987_yr1987, x1988_yr1988, 
         x1989_yr1989, x1990_yr1990, x1991_yr1991, 
         x1992_yr1992, x1993_yr1993, x1994_yr1994, 
         x1995_yr1995, x1996_yr1996, x1997_yr1997, 
         x1998_yr1998, x1999_yr1999, x2000_yr2000, 
         x2001_yr2001, x2002_yr2002, x2003_yr2003,
         x2004_yr2004, x2005_yr2005, x2006_yr2006,
         x2007_yr2007, x2008_yr2008, x2009_yr2009,
         x2010_yr2010, x2011_yr2011, x2012_yr2012,
         x2013_yr2013,
         x2014_yr2014, x2015_yr2015, x2016_yr2016,
         x2017_yr2017, x2018_yr2018, x2019_yr2019)


# creating new objects with different data sets and combining the ones that
# are similar to each other
 
# Using pivot longer to pivot the data for better view of the data

# mutating our year column to remove the na values. The values were not called

# "NA" when they were missing. Instead, they had "..", so I had to replace it

# with NA initially to later use na omit function

asialiteracymale <- worldbank %>%
  filter(series_name == 
"Literacy rate, adult male (% of males ages 15 and above)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

asialiteracyfemale <- worldbank %>%
  filter(series_name == 
"Literacy rate, adult female (% of females ages 15 and above)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

# joining both male and female data sets into a single tibble, using full_join
# to make sure I do not miss any missing data

# used substring to extract the first five strings in year excluding the first
# to convert it into a year value from the format I received the data in

asialiteracy <- full_join(asialiteracymale, asialiteracyfemale,
                          by = c("country_name", "year"),
                          suffix = c("male", "female")) %>%
  mutate(year = as.numeric(substr(.$year, 2, 5)))

education <- worldbank %>%
  filter(series_name == 
"Government expenditure on education, total (% of GDP)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

gdppercapita <- worldbank %>%
  filter(series_name == 
"GDP per capita (constant 2010 US$)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

gdpgrowth <- worldbank %>%
  filter(series_name == 
"GDP growth (annual %)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

# combining gdp growth, gdp per capita and gdp spending on education into a
# single tibble.
# Used full_join twice because the suffix could not have three values.
# Renamed the data column to education spending column for clarity
# Changed the year column to a numeric format alongside changing it into years

gdp <- full_join(gdppercapita, gdpgrowth,
                 by = c("country_name", "year"),
                 suffix = c("percapita", "growth")) %>%
  full_join(education, by = c("country_name", "year")) %>%
  rename("educationspending" = "data") %>%
  mutate(year = as.numeric(substr(.$year, 2, 5)))

enrollmentmale <- worldbank %>%
  filter(series_name == 
"Adjusted net enrollment rate, primary, male (% of primary school age children)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

enrollmentfemale <- worldbank %>%
  filter(series_name == 
"Adjusted net enrollment rate, primary, female (% of primary school age children)") %>%
  select(!series_name) %>%
  pivot_longer(!country_name, names_to = "year", values_to = "data") %>%
  mutate(data = ifelse(data == "..",
                       NA, data)) %>%
  na.omit()

primaryenrollment <- full_join(enrollmentmale, enrollmentfemale,
                               by = c("country_name", "year"),
                               suffix = c("male", "female")) %>%
  mutate(year = as.numeric(substr(.$year, 2, 5))) %>%
  mutate(datamale = as.numeric(datamale),
         datafemale = as.numeric(datafemale)) %>%
  mutate(enrollmentdifference = datamale - datafemale) %>%
  select(country_name, year, enrollmentdifference)

# creating a new column including the enrollment difference between men and
# women in primary education


```


```{r}

# saving the wrangled data sets into gif files for later extraction


# Adding an animation for gdp per capita over the years. Not including Maldives
# because it was too much of an outlier.

gdpgif <- gdp %>%
  filter(country_name != "Maldives") %>%
  mutate(datapercapita = as.numeric(datapercapita)) %>%
  ggplot(aes(year, datapercapita, group = country_name,
             color = factor(country_name))) +
  geom_line() +
  geom_point() +
  scale_color_manual(name = "Countries",
                     values = c("blue", "red", "yellow","cyan",
                                "purple", "green", "orange", "black")) +
  theme_classic() +
  theme(legend.position = "top") +
  scale_y_continuous(breaks = c(0, 500, 1000, 1500, 2000, 2500, 3000,
                                3500, 4000)) +
  scale_x_continuous(breaks = c(1960, 1970, 1980, 1990, 2000, 2010, 2020)) +
  transition_reveal(year) +
  labs(title = "GDP per capita over the years",
       subtitle = "Not including Maldives for being too much of an outlier",
       x = "Year",
       y = "GDP per capita")
  
anim_save("gdp.gif", animation = gdpgif)

# changing the column types to the necessary type for the ggplot

litgif <- asialiteracy %>%
  pivot_longer(cols = c(datamale, datafemale),
               names_to = "gender",
               values_to = "literacy") %>%
  mutate(literacy = as.numeric(literacy), gender = as.factor(gender),
         country_name = as.factor(country_name)) %>%
  ggplot(aes(year, literacy, group = gender, color = gender)) +
  geom_line() +
  geom_point(aes(group = seq_along(year))) +
  facet_wrap(~ country_name) +
  theme_bw() +
  scale_color_manual(values = c("red", "blue"),
                     breaks = c("datamale", "datafemale"),
                     labels = c("Male", "Female")) +
  labs(title = "Literacy rate for South Asian countries across gender",
       subtitle = "Female literacy has always been much lower generally",
       x = "Years",
       y = "Literacy rate") +
  transition_reveal(year)

anim_save("literacy.gif", litgif)

```


```{r}

# correlations across South Asian countries along the years

enrollmentgdp <- full_join(gdp, primaryenrollment,
                           by = c("country_name", "year"))

# correlation between gdp spending on education and the difference in primary
# enrollment between men and women

enrollmentgdp %>%
  select(country_name, year, enrollmentdifference, educationspending) %>%
  na.omit() %>%
  mutate(educationspending = as.numeric(educationspending)) %>%
  ggplot(aes(educationspending, enrollmentdifference)) +
  geom_point() +
  geom_smooth(method = "loess") +
  theme_clean() +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8),
                     labels = function(x) paste0(x, '%')) +
  scale_y_continuous(labels = function(x) paste0(x, '%')) +
  labs(title = "Correlation between GDP spending in education and the gender
              difference in primary school enrollment",
       x = "GDP spending in education",
       y = "Gender difference in primary enrollment")

enrollmentgdp %>%
  select(country_name, year, enrollmentdifference, datapercapita) %>%
  na.omit() %>%
  mutate(datapercapita = as.numeric(datapercapita)) %>%
  ggplot(aes(datapercapita, enrollmentdifference)) +
  geom_point() +
  geom_smooth(method = "loess") +
  theme_clean() +
  scale_x_continuous(breaks = c(0, 1000, 2000, 3000, 4000,
                                5000, 6000, 7000, 8000)) +
  scale_y_continuous(labels = function(x) paste0(x, '%')) +
  labs(title = "GDP per capita and gender difference in primary school 
       enrollment",
       x = "GDP per capita",
       y = "Gender difference in primary enrollment")
  
```


```{r}

# saving enrollment gdp into a csv for easier loading in the app

write.csv(enrollmentgdp, "enrollmentgdp")
write.csv(asialiteracy, "asialiteracy")

```

